---
kind: pipeline
type: kubernetes
name: Continuous Integration

platform:
  os: linux
  arch: amd64

steps:
- name: Setup environment
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - echo "$DEPLOYMENT_KEY" | base64 -d > /drone/src/key
  - chmod 400 /drone/src/key
  environment:
    DEPLOYMENT_KEY:
      from_secret: deployment-key

- name: Verify style and consistency
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - make lint

- name: Run unit tests
  pull: if-not-exists
  image: registry.bryk.io/general/golang:1.14
  commands:
  - make test

- name: Report result
  image: plugins/slack
  failure: ignore
  settings:
    webhook:
      from_secret: slack-webhook
    template: >
      {{#success build.status}}
        Build #{{build.number}} on repository {{repo.owner}}/{{repo.name}} succeeded.
        Author: {{build.author}}
        Branch: {{build.branch}}
        Build log is <{{build.link}}|available here>, commit <https://drone.bryk.io/link/{{repo.owner}}/{{repo.name}}/tree/refs/heads/{{build.branch}}?sha={{build.commit}}|source code> for more details.
      {{else}}
        Build #{{build.number}} on repository {{repo.owner}}/{{repo.name}} failed.
        Author: {{build.author}}
        Branch: {{build.branch}}
        Build log is <{{build.link}}|available here>, commit <https://drone.bryk.io/link/{{repo.owner}}/{{repo.name}}/tree/refs/heads/{{build.branch}}?sha={{build.commit}}|source code> for more details.
      {{/success}}

image_pull_secrets:
- bryk-io-registry

trigger:
  event:
  - push
  - tag

---
kind: signature
hmac: cce49eeb2959d147675bd1ed1cc633df688a5c7e7003a41ff80fcf237064c7cd

...
