{{- $fullName := include "cc.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cc.fullname" . }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.apiServer }}
  selector:
    matchLabels:
      {{- include "cc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cc.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullName }}
        {{- if .Values.tlsSecretName }}
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ printf "%s-storage" $fullName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/ct19
              name: config
            - mountPath: /home/guest/tls
              name: tls
              readOnly: true
          args:
            - server
          ports:
          - containerPort: 9090
            name: rpc
            protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-workers" $fullName }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.workers }}
  selector:
    matchLabels:
      {{- include "cc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cc.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullName }}
      containers:
        - name: main
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/ct19
              name: config
          args:
            - worker
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
