// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/server.proto

package protov1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *LocationRecord) Validate() error {
	return nil
}
