// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/tracking_server_api.proto

package protov1

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PingResponse struct {
	// Whether the service is reachable and healthy.
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()      { *m = PingResponse{} }
func (*PingResponse) ProtoMessage() {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{0}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return m.Size()
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type ActivationCodeRequest struct {
	// Identifier.
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// Account role.
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivationCodeRequest) Reset()      { *m = ActivationCodeRequest{} }
func (*ActivationCodeRequest) ProtoMessage() {}
func (*ActivationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{1}
}
func (m *ActivationCodeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActivationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActivationCodeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActivationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivationCodeRequest.Merge(m, src)
}
func (m *ActivationCodeRequest) XXX_Size() int {
	return m.Size()
}
func (m *ActivationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivationCodeRequest proto.InternalMessageInfo

func (m *ActivationCodeRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *ActivationCodeRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type ActivationCodeResponse struct {
	// Activation code generated.
	ActivationCode       string   `protobuf:"bytes,1,opt,name=activation_code,json=activationCode,proto3" json:"activation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivationCodeResponse) Reset()      { *m = ActivationCodeResponse{} }
func (*ActivationCodeResponse) ProtoMessage() {}
func (*ActivationCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{2}
}
func (m *ActivationCodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActivationCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActivationCodeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActivationCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivationCodeResponse.Merge(m, src)
}
func (m *ActivationCodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *ActivationCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivationCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivationCodeResponse proto.InternalMessageInfo

func (m *ActivationCodeResponse) GetActivationCode() string {
	if m != nil {
		return m.ActivationCode
	}
	return ""
}

type CredentialsRequest struct {
	// Identifier.
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// Account role.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Activation code previously obtained from the server.
	ActivationCode string `protobuf:"bytes,3,opt,name=activation_code,json=activationCode,proto3" json:"activation_code,omitempty"`
	// LD document containing a signed activation code.
	Proof                []byte   `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialsRequest) Reset()      { *m = CredentialsRequest{} }
func (*CredentialsRequest) ProtoMessage() {}
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{3}
}
func (m *CredentialsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CredentialsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsRequest.Merge(m, src)
}
func (m *CredentialsRequest) XXX_Size() int {
	return m.Size()
}
func (m *CredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsRequest proto.InternalMessageInfo

func (m *CredentialsRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *CredentialsRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *CredentialsRequest) GetActivationCode() string {
	if m != nil {
		return m.ActivationCode
	}
	return ""
}

func (m *CredentialsRequest) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type RenewCredentialsRequest struct {
	// Obtained when initially requesting the credential if it is renewable.
	RefreshCode          string   `protobuf:"bytes,1,opt,name=refresh_code,json=refreshCode,proto3" json:"refresh_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewCredentialsRequest) Reset()      { *m = RenewCredentialsRequest{} }
func (*RenewCredentialsRequest) ProtoMessage() {}
func (*RenewCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{4}
}
func (m *RenewCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RenewCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RenewCredentialsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RenewCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewCredentialsRequest.Merge(m, src)
}
func (m *RenewCredentialsRequest) XXX_Size() int {
	return m.Size()
}
func (m *RenewCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenewCredentialsRequest proto.InternalMessageInfo

func (m *RenewCredentialsRequest) GetRefreshCode() string {
	if m != nil {
		return m.RefreshCode
	}
	return ""
}

type CredentialsResponse struct {
	// Bearer credentials in the form of a JWT.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Set if the credential is refreshable. This code can be used
	// to obtain a new access token to replace an expired one.
	RefreshCode          string   `protobuf:"bytes,2,opt,name=refresh_code,json=refreshCode,proto3" json:"refresh_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialsResponse) Reset()      { *m = CredentialsResponse{} }
func (*CredentialsResponse) ProtoMessage() {}
func (*CredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{5}
}
func (m *CredentialsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CredentialsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialsResponse.Merge(m, src)
}
func (m *CredentialsResponse) XXX_Size() int {
	return m.Size()
}
func (m *CredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialsResponse proto.InternalMessageInfo

func (m *CredentialsResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CredentialsResponse) GetRefreshCode() string {
	if m != nil {
		return m.RefreshCode
	}
	return ""
}

type RecordRequest struct {
	// New location records to process.
	Records              []*LocationRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RecordRequest) Reset()      { *m = RecordRequest{} }
func (*RecordRequest) ProtoMessage() {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{6}
}
func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return m.Size()
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetRecords() []*LocationRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordResponse struct {
	// Whether the record(s) request was successfully received
	// and handled.
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordResponse) Reset()      { *m = RecordResponse{} }
func (*RecordResponse) ProtoMessage() {}
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1f8a97bd56b0960, []int{7}
}
func (m *RecordResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RecordResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResponse.Merge(m, src)
}
func (m *RecordResponse) XXX_Size() int {
	return m.Size()
}
func (m *RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResponse proto.InternalMessageInfo

func (m *RecordResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*PingResponse)(nil), "bryk.covid.proto.v1.PingResponse")
	proto.RegisterType((*ActivationCodeRequest)(nil), "bryk.covid.proto.v1.ActivationCodeRequest")
	proto.RegisterType((*ActivationCodeResponse)(nil), "bryk.covid.proto.v1.ActivationCodeResponse")
	proto.RegisterType((*CredentialsRequest)(nil), "bryk.covid.proto.v1.CredentialsRequest")
	proto.RegisterType((*RenewCredentialsRequest)(nil), "bryk.covid.proto.v1.RenewCredentialsRequest")
	proto.RegisterType((*CredentialsResponse)(nil), "bryk.covid.proto.v1.CredentialsResponse")
	proto.RegisterType((*RecordRequest)(nil), "bryk.covid.proto.v1.RecordRequest")
	proto.RegisterType((*RecordResponse)(nil), "bryk.covid.proto.v1.RecordResponse")
}

func init() { proto.RegisterFile("proto/v1/tracking_server_api.proto", fileDescriptor_f1f8a97bd56b0960) }

var fileDescriptor_f1f8a97bd56b0960 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6b, 0x13, 0x4d,
	0x1c, 0xc6, 0xdf, 0xd9, 0xf4, 0xc7, 0xfb, 0x4e, 0xf3, 0xc6, 0x3a, 0x69, 0xd3, 0x34, 0xca, 0x90,
	0x4e, 0x85, 0x86, 0xaa, 0x1b, 0x52, 0x0f, 0x42, 0xb1, 0x87, 0x26, 0x78, 0x10, 0x44, 0xc2, 0x5a,
	0x2a, 0x68, 0x21, 0x6c, 0x76, 0xa7, 0xdb, 0x21, 0xe9, 0xce, 0x3a, 0xbb, 0x8d, 0xf4, 0x56, 0xbc,
	0x0b, 0x82, 0x27, 0xaf, 0x9e, 0xc4, 0xbf, 0xc0, 0xa3, 0x47, 0xf1, 0x24, 0x78, 0xf1, 0xd8, 0x2c,
	0xfe, 0x01, 0x1e, 0x3d, 0xca, 0xcc, 0xce, 0xd6, 0x34, 0xdd, 0xaa, 0xbd, 0xcd, 0x3e, 0xf3, 0x7d,
	0xbe, 0xcf, 0x33, 0xe4, 0x13, 0x48, 0x02, 0xc1, 0x23, 0x5e, 0x1f, 0x34, 0xea, 0x91, 0xb0, 0x9d,
	0x1e, 0xf3, 0xbd, 0x4e, 0x48, 0xc5, 0x80, 0x8a, 0x8e, 0x1d, 0x30, 0x53, 0x5d, 0xa2, 0x62, 0x57,
	0x1c, 0xf6, 0x4c, 0x87, 0x0f, 0x98, 0x9b, 0x28, 0xe6, 0xa0, 0x51, 0xb9, 0xed, 0xb1, 0x68, 0xef,
	0xa0, 0x6b, 0x3a, 0x7c, 0xbf, 0xee, 0x71, 0x8f, 0xd7, 0x3d, 0xce, 0xbd, 0x3e, 0xb5, 0x03, 0x16,
	0xea, 0x63, 0xdd, 0x0e, 0x58, 0xdd, 0xf6, 0x7d, 0x1e, 0xd9, 0x11, 0xe3, 0x7e, 0x98, 0x78, 0x2b,
	0x37, 0xc7, 0x8d, 0x4a, 0xee, 0x1e, 0xec, 0xaa, 0xaf, 0xa4, 0x8e, 0x3c, 0xe9, 0xf1, 0x2b, 0x7a,
	0xd9, 0xc9, 0x14, 0xdd, 0x0f, 0xa2, 0x43, 0x7d, 0x39, 0x7f, 0xd2, 0x3e, 0x29, 0x9d, 0xc8, 0x04,
	0xc3, 0x7c, 0x9b, 0xf9, 0x9e, 0x45, 0xc3, 0x80, 0xfb, 0x21, 0x45, 0x05, 0x68, 0xf0, 0x5e, 0x19,
	0x54, 0x41, 0xed, 0x5f, 0xcb, 0xe0, 0x3d, 0xb2, 0x01, 0xe7, 0x37, 0x9d, 0x88, 0x0d, 0x54, 0xaf,
	0x16, 0x77, 0xa9, 0x45, 0x9f, 0x1e, 0xd0, 0x30, 0x42, 0xb3, 0x30, 0xe7, 0x32, 0x57, 0x4d, 0xfe,
	0x67, 0xc9, 0x23, 0x42, 0x70, 0x42, 0xf0, 0x3e, 0x2d, 0x1b, 0x4a, 0x52, 0x67, 0xb2, 0x09, 0x4b,
	0xe3, 0x76, 0x1d, 0xb4, 0x02, 0x2f, 0xd9, 0x27, 0x37, 0x1d, 0x87, 0xbb, 0x54, 0xef, 0x2a, 0xd8,
	0xa7, 0x0c, 0xe4, 0x10, 0xa2, 0x96, 0xa0, 0x2e, 0xf5, 0x23, 0x66, 0xf7, 0xc3, 0x0b, 0xc5, 0x67,
	0x85, 0xe4, 0xb2, 0x42, 0xd0, 0x1c, 0x9c, 0x0c, 0x04, 0xe7, 0xbb, 0xe5, 0x89, 0x2a, 0xa8, 0xe5,
	0xad, 0xe4, 0x83, 0xdc, 0x81, 0x0b, 0x16, 0xf5, 0xe9, 0xb3, 0x8c, 0xfc, 0x25, 0x98, 0x17, 0x74,
	0x57, 0xd0, 0x70, 0x6f, 0xb4, 0xfb, 0x8c, 0xd6, 0x54, 0xf1, 0x27, 0xb0, 0x78, 0xca, 0xa8, 0x1f,
	0xbe, 0x04, 0xf3, 0xb6, 0xe3, 0xd0, 0x30, 0xec, 0x44, 0xbc, 0x47, 0xfd, 0xd4, 0x99, 0x68, 0x5b,
	0x52, 0x3a, 0xb3, 0xdc, 0x38, 0xbb, 0xfc, 0x01, 0xfc, 0xdf, 0xa2, 0x0e, 0x17, 0x6e, 0x5a, 0x68,
	0x03, 0x4e, 0x0b, 0x25, 0x84, 0x65, 0x50, 0xcd, 0xd5, 0x66, 0xd6, 0x96, 0xcd, 0x0c, 0x16, 0xcd,
	0xfb, 0xdc, 0x51, 0xaf, 0xd6, 0xe6, 0xd4, 0x43, 0xaa, 0xb0, 0x90, 0xee, 0xcb, 0x26, 0x61, 0xed,
	0x68, 0x12, 0x5e, 0xde, 0xd2, 0xe0, 0x3f, 0x54, 0x08, 0x6d, 0xb6, 0xef, 0xa1, 0x47, 0x70, 0x42,
	0xf2, 0x83, 0x4a, 0x66, 0x02, 0x9f, 0x99, 0xc2, 0x67, 0xde, 0x95, 0xf0, 0x55, 0x96, 0x32, 0x5b,
	0x8c, 0x22, 0x47, 0xe6, 0x9e, 0x7f, 0xf9, 0xf6, 0xca, 0x28, 0xa0, 0xbc, 0x84, 0x53, 0xfe, 0x11,
	0x02, 0xb9, 0xf0, 0x05, 0x80, 0x85, 0xd3, 0xe8, 0xa0, 0xd5, 0xcc, 0x5d, 0x99, 0x78, 0x56, 0xae,
	0xff, 0xd5, 0xac, 0x6e, 0x40, 0x54, 0x83, 0xab, 0x64, 0x21, 0x6d, 0x30, 0x06, 0xcd, 0x3a, 0x58,
	0x45, 0x47, 0x00, 0xce, 0x8c, 0xfc, 0x9c, 0x68, 0x25, 0x33, 0xe0, 0x2c, 0x29, 0x95, 0xda, 0x9f,
	0x07, 0x75, 0x0d, 0xac, 0x6a, 0x94, 0x49, 0x31, 0xad, 0xe1, 0xfc, 0x1a, 0x92, 0x15, 0x5e, 0x02,
	0x38, 0x3b, 0xce, 0x23, 0xba, 0x91, 0xb9, 0xfe, 0x1c, 0x6c, 0x2f, 0x50, 0xe6, 0x9a, 0x2a, 0x83,
	0xc9, 0x62, 0x46, 0x99, 0x8e, 0x90, 0xeb, 0x65, 0xa5, 0x3e, 0x9c, 0x4a, 0xb0, 0x41, 0xe4, 0x9c,
	0x1e, 0x23, 0x8c, 0x56, 0x96, 0x7f, 0x3b, 0xa3, 0x83, 0x17, 0x55, 0x70, 0x91, 0x14, 0xd2, 0xe0,
	0x04, 0xd1, 0x75, 0xb0, 0xda, 0x7c, 0x0d, 0xbe, 0x0e, 0xf1, 0x3f, 0xc7, 0x43, 0x0c, 0xbe, 0x0f,
	0x31, 0xf8, 0x31, 0xc4, 0xe0, 0x28, 0xc6, 0xe0, 0x6d, 0x8c, 0xc1, 0xfb, 0x18, 0x83, 0x0f, 0x31,
	0x06, 0x1f, 0x63, 0x0c, 0x3e, 0xc7, 0x18, 0x1c, 0xc7, 0x18, 0xc0, 0x12, 0xe3, 0x59, 0x81, 0xcd,
	0xd2, 0x18, 0xc6, 0x01, 0x6b, 0xcb, 0xab, 0x36, 0x78, 0x3c, 0xad, 0x66, 0x06, 0x8d, 0x37, 0x46,
	0xae, 0xd9, 0x6a, 0xbf, 0x33, 0x8a, 0x4d, 0x69, 0x6f, 0x29, 0xbb, 0x9a, 0x31, 0xb7, 0x1b, 0x9f,
	0x12, 0x75, 0x47, 0xa9, 0x3b, 0x4a, 0xdd, 0xd9, 0x6e, 0x74, 0xa7, 0x94, 0xf5, 0xd6, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x57, 0x15, 0x55, 0x95, 0x26, 0x06, 0x00, 0x00,
}

func (this *PingResponse) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*PingResponse)
	if !ok {
		that2, ok := that.(PingResponse)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *PingResponse")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *PingResponse but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *PingResponse but is not nil && this == nil")
	}
	if this.Ok != that1.Ok {
		return fmt.Errorf("Ok this(%v) Not Equal that(%v)", this.Ok, that1.Ok)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *PingResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PingResponse)
	if !ok {
		that2, ok := that.(PingResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ok != that1.Ok {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ActivationCodeRequest) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*ActivationCodeRequest)
	if !ok {
		that2, ok := that.(ActivationCodeRequest)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *ActivationCodeRequest")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *ActivationCodeRequest but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *ActivationCodeRequest but is not nil && this == nil")
	}
	if this.Did != that1.Did {
		return fmt.Errorf("Did this(%v) Not Equal that(%v)", this.Did, that1.Did)
	}
	if this.Role != that1.Role {
		return fmt.Errorf("Role this(%v) Not Equal that(%v)", this.Role, that1.Role)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *ActivationCodeRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActivationCodeRequest)
	if !ok {
		that2, ok := that.(ActivationCodeRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Did != that1.Did {
		return false
	}
	if this.Role != that1.Role {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ActivationCodeResponse) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*ActivationCodeResponse)
	if !ok {
		that2, ok := that.(ActivationCodeResponse)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *ActivationCodeResponse")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *ActivationCodeResponse but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *ActivationCodeResponse but is not nil && this == nil")
	}
	if this.ActivationCode != that1.ActivationCode {
		return fmt.Errorf("ActivationCode this(%v) Not Equal that(%v)", this.ActivationCode, that1.ActivationCode)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *ActivationCodeResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ActivationCodeResponse)
	if !ok {
		that2, ok := that.(ActivationCodeResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ActivationCode != that1.ActivationCode {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *CredentialsRequest) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*CredentialsRequest)
	if !ok {
		that2, ok := that.(CredentialsRequest)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *CredentialsRequest")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *CredentialsRequest but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *CredentialsRequest but is not nil && this == nil")
	}
	if this.Did != that1.Did {
		return fmt.Errorf("Did this(%v) Not Equal that(%v)", this.Did, that1.Did)
	}
	if this.Role != that1.Role {
		return fmt.Errorf("Role this(%v) Not Equal that(%v)", this.Role, that1.Role)
	}
	if this.ActivationCode != that1.ActivationCode {
		return fmt.Errorf("ActivationCode this(%v) Not Equal that(%v)", this.ActivationCode, that1.ActivationCode)
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return fmt.Errorf("Proof this(%v) Not Equal that(%v)", this.Proof, that1.Proof)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *CredentialsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CredentialsRequest)
	if !ok {
		that2, ok := that.(CredentialsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Did != that1.Did {
		return false
	}
	if this.Role != that1.Role {
		return false
	}
	if this.ActivationCode != that1.ActivationCode {
		return false
	}
	if !bytes.Equal(this.Proof, that1.Proof) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RenewCredentialsRequest) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*RenewCredentialsRequest)
	if !ok {
		that2, ok := that.(RenewCredentialsRequest)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *RenewCredentialsRequest")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *RenewCredentialsRequest but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *RenewCredentialsRequest but is not nil && this == nil")
	}
	if this.RefreshCode != that1.RefreshCode {
		return fmt.Errorf("RefreshCode this(%v) Not Equal that(%v)", this.RefreshCode, that1.RefreshCode)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *RenewCredentialsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RenewCredentialsRequest)
	if !ok {
		that2, ok := that.(RenewCredentialsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RefreshCode != that1.RefreshCode {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *CredentialsResponse) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*CredentialsResponse)
	if !ok {
		that2, ok := that.(CredentialsResponse)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *CredentialsResponse")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *CredentialsResponse but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *CredentialsResponse but is not nil && this == nil")
	}
	if this.AccessToken != that1.AccessToken {
		return fmt.Errorf("AccessToken this(%v) Not Equal that(%v)", this.AccessToken, that1.AccessToken)
	}
	if this.RefreshCode != that1.RefreshCode {
		return fmt.Errorf("RefreshCode this(%v) Not Equal that(%v)", this.RefreshCode, that1.RefreshCode)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *CredentialsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CredentialsResponse)
	if !ok {
		that2, ok := that.(CredentialsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AccessToken != that1.AccessToken {
		return false
	}
	if this.RefreshCode != that1.RefreshCode {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RecordRequest) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*RecordRequest)
	if !ok {
		that2, ok := that.(RecordRequest)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *RecordRequest")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *RecordRequest but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *RecordRequest but is not nil && this == nil")
	}
	if len(this.Records) != len(that1.Records) {
		return fmt.Errorf("Records this(%v) Not Equal that(%v)", len(this.Records), len(that1.Records))
	}
	for i := range this.Records {
		if !this.Records[i].Equal(that1.Records[i]) {
			return fmt.Errorf("Records this[%v](%v) Not Equal that[%v](%v)", i, this.Records[i], i, that1.Records[i])
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *RecordRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RecordRequest)
	if !ok {
		that2, ok := that.(RecordRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Records) != len(that1.Records) {
		return false
	}
	for i := range this.Records {
		if !this.Records[i].Equal(that1.Records[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *RecordResponse) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*RecordResponse)
	if !ok {
		that2, ok := that.(RecordResponse)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *RecordResponse")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *RecordResponse but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *RecordResponse but is not nil && this == nil")
	}
	if this.Ok != that1.Ok {
		return fmt.Errorf("Ok this(%v) Not Equal that(%v)", this.Ok, that1.Ok)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *RecordResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RecordResponse)
	if !ok {
		that2, ok := that.(RecordResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Ok != that1.Ok {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *PingResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protov1.PingResponse{")
	s = append(s, "Ok: "+fmt.Sprintf("%#v", this.Ok)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActivationCodeRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protov1.ActivationCodeRequest{")
	s = append(s, "Did: "+fmt.Sprintf("%#v", this.Did)+",\n")
	s = append(s, "Role: "+fmt.Sprintf("%#v", this.Role)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ActivationCodeResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protov1.ActivationCodeResponse{")
	s = append(s, "ActivationCode: "+fmt.Sprintf("%#v", this.ActivationCode)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CredentialsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&protov1.CredentialsRequest{")
	s = append(s, "Did: "+fmt.Sprintf("%#v", this.Did)+",\n")
	s = append(s, "Role: "+fmt.Sprintf("%#v", this.Role)+",\n")
	s = append(s, "ActivationCode: "+fmt.Sprintf("%#v", this.ActivationCode)+",\n")
	s = append(s, "Proof: "+fmt.Sprintf("%#v", this.Proof)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RenewCredentialsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protov1.RenewCredentialsRequest{")
	s = append(s, "RefreshCode: "+fmt.Sprintf("%#v", this.RefreshCode)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CredentialsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&protov1.CredentialsResponse{")
	s = append(s, "AccessToken: "+fmt.Sprintf("%#v", this.AccessToken)+",\n")
	s = append(s, "RefreshCode: "+fmt.Sprintf("%#v", this.RefreshCode)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RecordRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protov1.RecordRequest{")
	if this.Records != nil {
		s = append(s, "Records: "+fmt.Sprintf("%#v", this.Records)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RecordResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&protov1.RecordResponse{")
	s = append(s, "Ok: "+fmt.Sprintf("%#v", this.Ok)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTrackingServerApi(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrackingServerAPIClient is the client API for TrackingServerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrackingServerAPIClient interface {
	// Reachability test.
	Ping(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*PingResponse, error)
	// Generate a new activation code.
	ActivationCode(ctx context.Context, in *ActivationCodeRequest, opts ...grpc.CallOption) (*ActivationCodeResponse, error)
	// Get access credentials for the platform.
	Credentials(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*CredentialsResponse, error)
	// Renew a previously-issued access credential.
	RenewCredentials(ctx context.Context, in *RenewCredentialsRequest, opts ...grpc.CallOption) (*CredentialsResponse, error)
	// Process location record events. A maximum value of 100 record
	// per-request is enforced.
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type trackingServerAPIClient struct {
	cc *grpc.ClientConn
}

func NewTrackingServerAPIClient(cc *grpc.ClientConn) TrackingServerAPIClient {
	return &trackingServerAPIClient{cc}
}

func (c *trackingServerAPIClient) Ping(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/bryk.covid.proto.v1.TrackingServerAPI/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServerAPIClient) ActivationCode(ctx context.Context, in *ActivationCodeRequest, opts ...grpc.CallOption) (*ActivationCodeResponse, error) {
	out := new(ActivationCodeResponse)
	err := c.cc.Invoke(ctx, "/bryk.covid.proto.v1.TrackingServerAPI/ActivationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServerAPIClient) Credentials(ctx context.Context, in *CredentialsRequest, opts ...grpc.CallOption) (*CredentialsResponse, error) {
	out := new(CredentialsResponse)
	err := c.cc.Invoke(ctx, "/bryk.covid.proto.v1.TrackingServerAPI/Credentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServerAPIClient) RenewCredentials(ctx context.Context, in *RenewCredentialsRequest, opts ...grpc.CallOption) (*CredentialsResponse, error) {
	out := new(CredentialsResponse)
	err := c.cc.Invoke(ctx, "/bryk.covid.proto.v1.TrackingServerAPI/RenewCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackingServerAPIClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/bryk.covid.proto.v1.TrackingServerAPI/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrackingServerAPIServer is the server API for TrackingServerAPI service.
type TrackingServerAPIServer interface {
	// Reachability test.
	Ping(context.Context, *types.Empty) (*PingResponse, error)
	// Generate a new activation code.
	ActivationCode(context.Context, *ActivationCodeRequest) (*ActivationCodeResponse, error)
	// Get access credentials for the platform.
	Credentials(context.Context, *CredentialsRequest) (*CredentialsResponse, error)
	// Renew a previously-issued access credential.
	RenewCredentials(context.Context, *RenewCredentialsRequest) (*CredentialsResponse, error)
	// Process location record events. A maximum value of 100 record
	// per-request is enforced.
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
}

// UnimplementedTrackingServerAPIServer can be embedded to have forward compatible implementations.
type UnimplementedTrackingServerAPIServer struct {
}

func (*UnimplementedTrackingServerAPIServer) Ping(ctx context.Context, req *types.Empty) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedTrackingServerAPIServer) ActivationCode(ctx context.Context, req *ActivationCodeRequest) (*ActivationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivationCode not implemented")
}
func (*UnimplementedTrackingServerAPIServer) Credentials(ctx context.Context, req *CredentialsRequest) (*CredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Credentials not implemented")
}
func (*UnimplementedTrackingServerAPIServer) RenewCredentials(ctx context.Context, req *RenewCredentialsRequest) (*CredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCredentials not implemented")
}
func (*UnimplementedTrackingServerAPIServer) Record(ctx context.Context, req *RecordRequest) (*RecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Record not implemented")
}

func RegisterTrackingServerAPIServer(s *grpc.Server, srv TrackingServerAPIServer) {
	s.RegisterService(&_TrackingServerAPI_serviceDesc, srv)
}

func _TrackingServerAPI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerAPIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bryk.covid.proto.v1.TrackingServerAPI/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerAPIServer).Ping(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingServerAPI_ActivationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerAPIServer).ActivationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bryk.covid.proto.v1.TrackingServerAPI/ActivationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerAPIServer).ActivationCode(ctx, req.(*ActivationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingServerAPI_Credentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerAPIServer).Credentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bryk.covid.proto.v1.TrackingServerAPI/Credentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerAPIServer).Credentials(ctx, req.(*CredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingServerAPI_RenewCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerAPIServer).RenewCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bryk.covid.proto.v1.TrackingServerAPI/RenewCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerAPIServer).RenewCredentials(ctx, req.(*RenewCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrackingServerAPI_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackingServerAPIServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bryk.covid.proto.v1.TrackingServerAPI/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackingServerAPIServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrackingServerAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bryk.covid.proto.v1.TrackingServerAPI",
	HandlerType: (*TrackingServerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TrackingServerAPI_Ping_Handler,
		},
		{
			MethodName: "ActivationCode",
			Handler:    _TrackingServerAPI_ActivationCode_Handler,
		},
		{
			MethodName: "Credentials",
			Handler:    _TrackingServerAPI_Credentials_Handler,
		},
		{
			MethodName: "RenewCredentials",
			Handler:    _TrackingServerAPI_RenewCredentials_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _TrackingServerAPI_Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/tracking_server_api.proto",
}

func (m *PingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Ok {
		i--
		if m.Ok {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ActivationCodeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActivationCodeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActivationCodeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Role) > 0 {
		i -= len(m.Role)
		copy(dAtA[i:], m.Role)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.Role)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActivationCodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActivationCodeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActivationCodeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ActivationCode) > 0 {
		i -= len(m.ActivationCode)
		copy(dAtA[i:], m.ActivationCode)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.ActivationCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CredentialsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CredentialsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CredentialsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ActivationCode) > 0 {
		i -= len(m.ActivationCode)
		copy(dAtA[i:], m.ActivationCode)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.ActivationCode)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Role) > 0 {
		i -= len(m.Role)
		copy(dAtA[i:], m.Role)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.Role)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RenewCredentialsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RenewCredentialsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RenewCredentialsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RefreshCode) > 0 {
		i -= len(m.RefreshCode)
		copy(dAtA[i:], m.RefreshCode)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.RefreshCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CredentialsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CredentialsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CredentialsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.RefreshCode) > 0 {
		i -= len(m.RefreshCode)
		copy(dAtA[i:], m.RefreshCode)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.RefreshCode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AccessToken) > 0 {
		i -= len(m.AccessToken)
		copy(dAtA[i:], m.AccessToken)
		i = encodeVarintTrackingServerApi(dAtA, i, uint64(len(m.AccessToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RecordRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RecordRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RecordRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Records) > 0 {
		for iNdEx := len(m.Records) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Records[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTrackingServerApi(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RecordResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RecordResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RecordResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Ok {
		i--
		if m.Ok {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrackingServerApi(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrackingServerApi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedPingResponse(r randyTrackingServerApi, easy bool) *PingResponse {
	this := &PingResponse{}
	this.Ok = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 2)
	}
	return this
}

func NewPopulatedActivationCodeRequest(r randyTrackingServerApi, easy bool) *ActivationCodeRequest {
	this := &ActivationCodeRequest{}
	this.Did = string(randStringTrackingServerApi(r))
	this.Role = string(randStringTrackingServerApi(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 3)
	}
	return this
}

func NewPopulatedActivationCodeResponse(r randyTrackingServerApi, easy bool) *ActivationCodeResponse {
	this := &ActivationCodeResponse{}
	this.ActivationCode = string(randStringTrackingServerApi(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 2)
	}
	return this
}

func NewPopulatedCredentialsRequest(r randyTrackingServerApi, easy bool) *CredentialsRequest {
	this := &CredentialsRequest{}
	this.Did = string(randStringTrackingServerApi(r))
	this.Role = string(randStringTrackingServerApi(r))
	this.ActivationCode = string(randStringTrackingServerApi(r))
	v1 := r.Intn(100)
	this.Proof = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Proof[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 5)
	}
	return this
}

func NewPopulatedRenewCredentialsRequest(r randyTrackingServerApi, easy bool) *RenewCredentialsRequest {
	this := &RenewCredentialsRequest{}
	this.RefreshCode = string(randStringTrackingServerApi(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 2)
	}
	return this
}

func NewPopulatedCredentialsResponse(r randyTrackingServerApi, easy bool) *CredentialsResponse {
	this := &CredentialsResponse{}
	this.AccessToken = string(randStringTrackingServerApi(r))
	this.RefreshCode = string(randStringTrackingServerApi(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 3)
	}
	return this
}

func NewPopulatedRecordRequest(r randyTrackingServerApi, easy bool) *RecordRequest {
	this := &RecordRequest{}
	if r.Intn(5) != 0 {
		v2 := r.Intn(5)
		this.Records = make([]*LocationRecord, v2)
		for i := 0; i < v2; i++ {
			this.Records[i] = NewPopulatedLocationRecord(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 2)
	}
	return this
}

func NewPopulatedRecordResponse(r randyTrackingServerApi, easy bool) *RecordResponse {
	this := &RecordResponse{}
	this.Ok = bool(bool(r.Intn(2) == 0))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTrackingServerApi(r, 2)
	}
	return this
}

type randyTrackingServerApi interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTrackingServerApi(r randyTrackingServerApi) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringTrackingServerApi(r randyTrackingServerApi) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneTrackingServerApi(r)
	}
	return string(tmps)
}
func randUnrecognizedTrackingServerApi(r randyTrackingServerApi, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldTrackingServerApi(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldTrackingServerApi(dAtA []byte, r randyTrackingServerApi, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateTrackingServerApi(dAtA, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		dAtA = encodeVarintPopulateTrackingServerApi(dAtA, uint64(v4))
	case 1:
		dAtA = encodeVarintPopulateTrackingServerApi(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateTrackingServerApi(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateTrackingServerApi(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateTrackingServerApi(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateTrackingServerApi(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *PingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ok {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ActivationCodeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	l = len(m.Role)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ActivationCodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ActivationCode)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CredentialsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	l = len(m.Role)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	l = len(m.ActivationCode)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RenewCredentialsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RefreshCode)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CredentialsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccessToken)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	l = len(m.RefreshCode)
	if l > 0 {
		n += 1 + l + sovTrackingServerApi(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RecordRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Records) > 0 {
		for _, e := range m.Records {
			l = e.Size()
			n += 1 + l + sovTrackingServerApi(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RecordResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ok {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTrackingServerApi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrackingServerApi(x uint64) (n int) {
	return sovTrackingServerApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *PingResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingResponse{`,
		`Ok:` + fmt.Sprintf("%v", this.Ok) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActivationCodeRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActivationCodeRequest{`,
		`Did:` + fmt.Sprintf("%v", this.Did) + `,`,
		`Role:` + fmt.Sprintf("%v", this.Role) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ActivationCodeResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ActivationCodeResponse{`,
		`ActivationCode:` + fmt.Sprintf("%v", this.ActivationCode) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CredentialsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CredentialsRequest{`,
		`Did:` + fmt.Sprintf("%v", this.Did) + `,`,
		`Role:` + fmt.Sprintf("%v", this.Role) + `,`,
		`ActivationCode:` + fmt.Sprintf("%v", this.ActivationCode) + `,`,
		`Proof:` + fmt.Sprintf("%v", this.Proof) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RenewCredentialsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RenewCredentialsRequest{`,
		`RefreshCode:` + fmt.Sprintf("%v", this.RefreshCode) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CredentialsResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CredentialsResponse{`,
		`AccessToken:` + fmt.Sprintf("%v", this.AccessToken) + `,`,
		`RefreshCode:` + fmt.Sprintf("%v", this.RefreshCode) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RecordRequest) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForRecords := "[]*LocationRecord{"
	for _, f := range this.Records {
		repeatedStringForRecords += strings.Replace(fmt.Sprintf("%v", f), "LocationRecord", "LocationRecord", 1) + ","
	}
	repeatedStringForRecords += "}"
	s := strings.Join([]string{`&RecordRequest{`,
		`Records:` + repeatedStringForRecords + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RecordResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RecordResponse{`,
		`Ok:` + fmt.Sprintf("%v", this.Ok) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTrackingServerApi(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *PingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ok", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ok = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActivationCodeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActivationCodeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActivationCodeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Role = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActivationCodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActivationCodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActivationCodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivationCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CredentialsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CredentialsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CredentialsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Role = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivationCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RenewCredentialsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RenewCredentialsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RenewCredentialsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefreshCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefreshCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CredentialsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CredentialsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CredentialsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccessToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccessToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefreshCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefreshCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RecordRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RecordRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RecordRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Records", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Records = append(m.Records, &LocationRecord{})
			if err := m.Records[len(m.Records)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RecordResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RecordResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RecordResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ok", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Ok = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTrackingServerApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrackingServerApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrackingServerApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrackingServerApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrackingServerApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrackingServerApi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTrackingServerApi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTrackingServerApi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTrackingServerApi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrackingServerApi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTrackingServerApi = fmt.Errorf("proto: unexpected end of group")
)
