// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/v1/tracking_server_api.proto

package protov1

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PingResponse) Validate() error {
	return nil
}
func (this *ActivationCodeRequest) Validate() error {
	return nil
}
func (this *ActivationCodeResponse) Validate() error {
	return nil
}
func (this *CredentialsRequest) Validate() error {
	return nil
}
func (this *RenewCredentialsRequest) Validate() error {
	return nil
}
func (this *CredentialsResponse) Validate() error {
	return nil
}
func (this *RecordRequest) Validate() error {
	for _, item := range this.Records {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Records", err)
			}
		}
	}
	return nil
}
func (this *RecordResponse) Validate() error {
	return nil
}
